### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$HOME/autoload'

### ISSUE THREAD

**Issue by inancgumus** [benjaminRomano/grunt-manager#1]
**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.4
**Thrown From**: [grunt-manager](https://github.com/benjaminRomano/grunt-manager) package, v0.1.5
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '$HOME/autoload'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '$HOME/autoload'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at findFilesHelper ($HOME/.atom/packages/grunt-manager/lib/file-finder-util.coffee:37:15)
  at $HOME/.atom/packages/grunt-manager/lib/file-finder-util.coffee:20:22
  at Array.map (native)
  at FileFinderUtil.findFiles ($HOME/.atom/packages/grunt-manager/lib/file-finder-util.coffee:20:8)
  at GruntView.createGruntfileList ($HOME/.atom/packages/grunt-manager/lib/views/grunt-view.coffee:20:5)
  at GruntView.initialize ($HOME/.atom/packages/grunt-manager/lib/views/grunt-view.coffee:16:6)
  at GruntView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new GruntView ($HOME/.atom/packages/grunt-manager/lib/views/grunt-view.coffee:7:3)
  at Object.content ($HOME/.atom/packages/grunt-manager/lib/views/grunt-pane.coffee:11:33)
  at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
  at Function.View.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
  at Function.GruntPane.content ($HOME/.atom/packages/grunt-manager/lib/views/grunt-pane.coffee:9:6)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
  at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at GruntPane.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
  at GruntPane.DockPaneView ($HOME/.atom/packages/grunt-manager/node_modules/atom-bottom-dock/lib/dock-pane-view.coffee:4:3)
  at new GruntPane ($HOME/.atom/packages/grunt-manager/lib/views/grunt-pane.coffee:8:3)
  at Object.module.exports.add ($HOME/.atom/packages/grunt-manager/lib/main.coffee:28:19)
  at Object.module.exports.consumeBottomDock ($HOME/.atom/packages/grunt-manager/lib/main.coffee:23:6)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at process._tickCallback (node.js:357:13)

```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-light"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-backbone, v0.6.1
atom-material-syntax-light, v0.0.3
atom-material-ui, v0.6.0
atom-pair, v2.0.9
atom-runner, v2.4.3
atom-spotify2, v2.1.2
atom-wallaby, v1.0.4
autocomplete-html-entities, v0.1.0
bottom-dock, v0.3.3
change-case, v0.6.0
coffee-refactor, v0.7.0
emmet, v2.3.12
grunt-manager, v0.1.5
grunt-runner, v0.11.0
js-refactor, v0.4.2
jshint, v1.6.1
linter, v1.5.0
linter-coffeelint, v1.0.2
linter-csslint, v1.0.5
linter-jshint, v1.1.5
linter-manager, v0.2.2
linter-tidy, v1.0.1
pigments, v0.13.2
refactor, v0.5.1
sync-settings, v0.6.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
Does $HOME/autoload exist?

**Comment by inancgumus** [comment]
Nope.

**Comment by benjaminRomano** [comment]
Not sure what's causing this error... Is there any other info that you could give me that might help me figure out the problem?

**Comment by inancgumus** [comment]
Of course, what else do you need? I'm not knowledgable about it so better to say that yourself, sorry.

**Comment by benjaminRomano** [comment]
What projects do you have open in the tree-view when you get this error? Does this error happen every time you start up grunt-manager or only with specific files?

Also do you have any symlinked files/folders in your project?

**Comment by benjaminRomano** [comment]
I think I found the cause of the error. I pushed out a new version (v0.1.6) that should hopefully fix it. 

Can you see if this fixes your problem. Thanks
